### ISSUE TITLE
Prepend SHA256d with an all zero block

### ISSUE THREAD

**Issue by ivochkin** [DevJPM/CryptoJPM#4]
An open question is whether this feature should be implemented in CryptoJPM (and crypto++ finally) or not.

For details, see related pull request in pycrypto project: https://github.com/dlitz/pycrypto/pull/127

**Comment by DevJPM** [comment]
I just re-read the parts in the book and saw that you're right about double-hashing and prepending zeros.
This implementation of double-hash will prepend zeroes.
I'd say we prepend a blockszie of zeroes, if we know the blocksize and if not just the double digestsize (for SHA-3 which doesn't seem to have a Blocksize...)

**Comment by DevJPM** [comment]
Give me ~24 hours to add the patch for prepending the zeroes.
Your pull request will be merged.
